In [0]:
from google.colab import files
u = files.upload()

Saving sample_submission.csv to sample_submission.csv
Saving test.csv to test.csv
Saving train.csv to train.csv

In [1]:
import pandas as pd
train = pd.read_csv("train.csv")

In [2]:
train.dtypes

label       int64
pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
pixel4      int64
pixel5      int64
pixel6      int64
pixel7      int64
pixel8      int64
pixel9      int64
pixel10     int64
pixel11     int64
pixel12     int64
pixel13     int64
pixel14     int64
pixel15     int64
pixel16     int64
pixel17     int64
pixel18     int64
pixel19     int64
pixel20     int64
pixel21     int64
pixel22     int64
pixel23     int64
pixel24     int64
pixel25     int64
pixel26     int64
pixel27     int64
pixel28     int64
            ...
pixel754    int64
pixel755    int64
pixel756    int64
pixel757    int64
pixel758    int64
pixel759    int64
pixel760    int64
pixel761    int64
pixel762    int64
pixel763    int64
pixel764    int64
pixel765    int64
pixel766    int64
pixel767    int64
pixel768    int64
pixel769    int64
pixel770    int64
pixel771    int64
pixel772    int64
pixel773    int64
pixel774    int64
pixel775    int64
pixel776    int64
pixel777    int64
pixel778    int64
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 785, dtype: object

In [3]:
y = train['label']
x = train.iloc[:,1:]

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0)

In [5]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
clf.fit(x_train,y_train)
y1 = clf.predict(x_test)
x_test.dtypes

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
pixel4      int64
pixel5      int64
pixel6      int64
pixel7      int64
pixel8      int64
pixel9      int64
pixel10     int64
pixel11     int64
pixel12     int64
pixel13     int64
pixel14     int64
pixel15     int64
pixel16     int64
pixel17     int64
pixel18     int64
pixel19     int64
pixel20     int64
pixel21     int64
pixel22     int64
pixel23     int64
pixel24     int64
pixel25     int64
pixel26     int64
pixel27     int64
pixel28     int64
pixel29     int64
            ...
pixel754    int64
pixel755    int64
pixel756    int64
pixel757    int64
pixel758    int64
pixel759    int64
pixel760    int64
pixel761    int64
pixel762    int64
pixel763    int64
pixel764    int64
pixel765    int64
pixel766    int64
pixel767    int64
pixel768    int64
pixel769    int64
pixel770    int64
pixel771    int64
pixel772    int64
pixel773    int64
pixel774    int64
pixel775    int64
pixel776    int64
pixel777    int64
pixel778    int64
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 784, dtype: object

In [6]:
pd.crosstab(y1,y_test)

label    0     1     2    3    4    5     6     7    8    9
row_0
0      983     0    11    6    3    9     8     2    6   10
1        0  1170     2    1    4    4     2    11    9    3
2        5     7  1022   18    3    1     3    25   13    5
3        2     6    10  979    1   35     1     5   29   10
4        3     0     2    3  977   10     4    17   16   31
5        6     3     1   25    3  847    14     3   22    8
6        9     1     5    4    9   11  1007     1   10    0
7        2     1     8   12    3    2     0  1044    5   14
8        3     2    13   16    3    8     5     3  873    8
9        2     0     3    6   28    3     0    18   12  927

In [7]:
y2 = clf.predict(x_train)
pd.crosstab(y2,y_train)

label     0     1     2     3     4     5     6     7     8     9
row_0
0      3117     0     1     0     0     2     0     0     0     0
1         0  3492     1     1     0     0     0     1     2     0
2         0     0  3096     3     0     0     1     0     0     0
3         0     1     0  3275     0     1     0     0     2     0
4         0     0     1     0  3034     0     0     2     0     2
5         0     0     0     0     0  2862     0     0     0     2
6         0     0     0     0     1     0  3092     0     0     0
7         0     1     1     1     1     0     0  3267     0     3
8         0     0     0     1     0     0     0     1  3063     1
9         0     0     0     0     2     0     0     1     1  3164

In [9]:
from sklearn.metrics import jaccard_score
pred = jaccard_score(y1,y_test,average = 'samples')
pred

ValueError: Samplewise metrics are not available outside of multilabel classification.

In [8]:
test= pd.read_csv("test.csv")
test.dtypes

pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
pixel4      int64
pixel5      int64
pixel6      int64
pixel7      int64
pixel8      int64
pixel9      int64
pixel10     int64
pixel11     int64
pixel12     int64
pixel13     int64
pixel14     int64
pixel15     int64
pixel16     int64
pixel17     int64
pixel18     int64
pixel19     int64
pixel20     int64
pixel21     int64
pixel22     int64
pixel23     int64
pixel24     int64
pixel25     int64
pixel26     int64
pixel27     int64
pixel28     int64
pixel29     int64
            ...
pixel754    int64
pixel755    int64
pixel756    int64
pixel757    int64
pixel758    int64
pixel759    int64
pixel760    int64
pixel761    int64
pixel762    int64
pixel763    int64
pixel764    int64
pixel765    int64
pixel766    int64
pixel767    int64
pixel768    int64
pixel769    int64
pixel770    int64
pixel771    int64
pixel772    int64
pixel773    int64
pixel774    int64
pixel775    int64
pixel776    int64
pixel777    int64
pixel778    int64
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 784, dtype: object

In [9]:
x= test.iloc[:,0:]
y1 = clf.predict(x)
x.dtypes

pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
pixel4      int64
pixel5      int64
pixel6      int64
pixel7      int64
pixel8      int64
pixel9      int64
pixel10     int64
pixel11     int64
pixel12     int64
pixel13     int64
pixel14     int64
pixel15     int64
pixel16     int64
pixel17     int64
pixel18     int64
pixel19     int64
pixel20     int64
pixel21     int64
pixel22     int64
pixel23     int64
pixel24     int64
pixel25     int64
pixel26     int64
pixel27     int64
pixel28     int64
pixel29     int64
            ...
pixel754    int64
pixel755    int64
pixel756    int64
pixel757    int64
pixel758    int64
pixel759    int64
pixel760    int64
pixel761    int64
pixel762    int64
pixel763    int64
pixel764    int64
pixel765    int64
pixel766    int64
pixel767    int64
pixel768    int64
pixel769    int64
pixel770    int64
pixel771    int64
pixel772    int64
pixel773    int64
pixel774    int64
pixel775    int64
pixel776    int64
pixel777    int64
pixel778    int64
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 784, dtype: object

In [10]:
samp = pd.read_csv("sample_submission.csv")
samp.dtypes
samp['ImageId'].value_counts()

2047     1
11567    1
17698    1
19747    1
25894    1
27943    1
5416     1
7465     1
1322     1
3371     1
13612    1
15661    1
9518     1
21824    1
11599    1
23873    1
17730    1
19779    1
25926    1
27975    1
5448     1
7497     1
1354     1
3403     1
13644    1
15693    1
23841    1
21792    1
11535    1
9486     1
        ..
15090    1
13043    1
27320    1
6838     1
25209    1
693      1
19068    1
17021    1
23166    1
21119    1
10896    1
8849     1
14994    1
12947    1
2708     1
661      1
6806     1
4759     1
27288    1
25241    1
19100    1
17053    1
23198    1
21151    1
10928    1
8881     1
15026    1
12979    1
2740     1
2049     1
Name: ImageId, Length: 28000, dtype: int64

In [11]:
train.dtypes
test.dtypes

pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
pixel4      int64
pixel5      int64
pixel6      int64
pixel7      int64
pixel8      int64
pixel9      int64
pixel10     int64
pixel11     int64
pixel12     int64
pixel13     int64
pixel14     int64
pixel15     int64
pixel16     int64
pixel17     int64
pixel18     int64
pixel19     int64
pixel20     int64
pixel21     int64
pixel22     int64
pixel23     int64
pixel24     int64
pixel25     int64
pixel26     int64
pixel27     int64
pixel28     int64
pixel29     int64
            ...
pixel754    int64
pixel755    int64
pixel756    int64
pixel757    int64
pixel758    int64
pixel759    int64
pixel760    int64
pixel761    int64
pixel762    int64
pixel763    int64
pixel764    int64
pixel765    int64
pixel766    int64
pixel767    int64
pixel768    int64
pixel769    int64
pixel770    int64
pixel771    int64
pixel772    int64
pixel773    int64
pixel774    int64
pixel775    int64
pixel776    int64
pixel777    int64
pixel778    int64
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 784, dtype: object

In [12]:
test['Label'] = clf.predict(x)

In [13]:
test['Label'].to_csv("submit.csv",index=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [ ]:
from google.colab import drive
drive.mount('drive')
test['Label'].to_csv("submit.csv",index=True)
!cp submit.csv drive/My\ Drive/

In [17]:
from sklearn.svm import SVC
SVC = SVC(C=2,kernel = 'poly',verbose = True)
SVC.fit(x_train,y_train)

# y2 = s.predict(x_test)
# pd.crosstab(y_test,y2)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

[LibSVM]

SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=True)

In [18]:
test23 = SVC.predict(x_test)
pd.crosstab(test23,y_test)

label    0     1     2     3     4    5     6     7    8    9
row_0
0      995     0     5     0     2    1     3     1    3    7
1        0  1178     1     0     4    0     0     5    5    4
2        5     5  1050    11     0    2     0     8    7    2
3        0     2     5  1029     0    6     0     2   14    3
4        1     0     1     0  1008    1     2     2    2    9
5        4     2     3    12     1  900     3     1    5    3
6        5     0     1     0     5    9  1033     0    4    0
7        0     0     5     4     2    0     0  1101    2   16
8        5     3     6    10     0    8     3     3  950    3
9        0     0     0     4    12    3     0     6    3  969

In [19]:
test['Label'] = SVC.predict(x)
test['Label'].to_csv("submit.csv",index=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [16]:
# print(s)
s.summary()

AttributeError: 'SVC' object has no attribute 'summary'